"""initial schema

Revision ID: 155227c01edc
Revises:
Create Date: 2026-06-22 13:04:55.535370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "155227c01edc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column("tin", sa.String(), nullable=False),
        sa.Column("party_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("telephone", sa.String(), nullable=False),
        sa.Column("street_name", sa.String(), nullable=False),
        sa.Column("city_name", sa.String(), nullable=False),
        sa.Column("postal_zone", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("lga", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customers_business_id"),
        "customers",
        ["business_id"],
        unique=False,
    )
    op.create_table(
        "invoice_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column("irn", sa.String(), nullable=False),
        sa.Column("issue_date", sa.String(), nullable=False),
        sa.Column("customer_name", sa.String(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("payment_status", sa.String(), nullable=False),
        sa.Column("payable_amount", sa.Float(), nullable=False),
        sa.Column("transmitted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "business_id", "irn", name="uq_invoice_log_business_irn"
        ),
    )
    op.create_index(
        op.f("ix_invoice_log_business_id"),
        "invoice_log",
        ["business_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_log_irn"), "invoice_log", ["irn"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column("service_id", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("user_secret", sa.String(), nullable=True),
        sa.Column("certificate", sa.String(), nullable=True),
        sa.Column("public_key", sa.String(), nullable=True),
        sa.Column("tin", sa.String(), nullable=True),
        sa.Column("party_name", sa.String(), nullable=True),
        sa.Column("telephone", sa.String(), nullable=True),
        sa.Column("street_name", sa.String(), nullable=True),
        sa.Column("city_name", sa.String(), nullable=True),
        sa.Column("postal_zone", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("lga", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_business_id"), "users", ["business_id"], unique=False
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_service_id"), "users", ["service_id"], unique=False
    )
    op.create_index(
        op.f("ix_users_username"), "users", ["username"], unique=False
    )
    op.create_table(
        "session_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("jwt_token", sa.String(), nullable=False),
        sa.Column("user_secret", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("business_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.String(), nullable=False),
        sa.Column("wizard_json", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_state_session_id"),
        "session_state",
        ["session_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_session_state_session_id"), table_name="session_state"
    )
    op.drop_table("session_state")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_service_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_business_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_invoice_log_irn"), table_name="invoice_log")
    op.drop_index(op.f("ix_invoice_log_business_id"), table_name="invoice_log")
    op.drop_table("invoice_log")
    op.drop_index(op.f("ix_customers_business_id"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###